export interface LineConfig {token:string;secret:string;loginChannelId:string;liffId:string;ownerId:string;cronSecret:string;enabled:boolean}
export async function verifySignature(raw:string,signature:string|null,secret:string){if(!signature||!secret)return false;try{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const decoded=Uint8Array.from(atob(signature),c=>c.charCodeAt(0));return await crypto.subtle.verify('HMAC',key,decoded,new TextEncoder().encode(raw))}catch{return false}}
export async function verifyLineToken(token:string,channelId:string,fetcher:typeof fetch=fetch){if(!channelId||!token||token.length>10000)throw Error('LINE_AUTH_REQUIRED');const result=await fetcher('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:token,client_id:channelId}),signal:AbortSignal.timeout(10000)});if(!result.ok)throw Error('LINE_AUTH_INVALID');const data:any=await result.json();if(data.iss!=='https://access.line.me'||data.aud!==channelId||!/^U[0-9a-f]{32}$/.test(data.sub)||data.exp*1000<=Date.now())throw Error('LINE_AUTH_INVALID');return data.sub as string}
export function retryDecision(code:number,acceptedId:string|null){if(code===200||code===409&&acceptedId)return 'accepted';if(code===429||code>=500||code===0)return 'retry';return 'failed'}
export function retryWindowValid(firstAttempt:string,now=Date.now()){return now-new Date(firstAttempt).getTime()<23*60*60*1000}
export function reminderText(r:{name:string;plate:string;province:string;years:number},v:{kind:string;due:string}){const date=new Date(v.due+'T00:00:00Z').toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Bangkok'});return `BJ Carcare แจ้งเตือนรอบดูแลครับ 🚗\nสวัสดีคุณ${r.name}\nรถทะเบียน ${r.plate} ${r.province}\nแพ็กเกจเซรามิก ${r.years} ปี\nถึงรอบ${v.kind==='recoat'?'บำรุงรักษาใหญ่ พร้อมทำ Recoat':'เช็คระยะทุก 3 เดือน'} วันที่ ${date}\nตอบกลับแชทเพื่อนัดหมายกับร้านได้เลยครับ`}
const clean=(value:string,max:number)=>value.replace(/\s+/g,' ').trim().slice(0,max);
const selectedServices=(services:string)=>{const labels:Record<string,string>={ceramic:'เคลือบเซรามิก',seat:'ซักเบาะ',carpet:'ซักพรม'};try{return (JSON.parse(services) as string[]).map(s=>labels[s]).filter(Boolean).join(', ')}catch{return 'บริการรถยนต์'}};
export function registrationReceivedText(r:{name:string;plate:string;province:string;services:string}){return `BJ Carcare รับข้อมูลลงทะเบียนแล้วครับ ✅\nคุณ${clean(r.name,80)} · รถทะเบียน ${clean(r.plate,30)} ${clean(r.province,60)}\nบริการที่เลือก: ${selectedServices(r.services)}\nร้านจะตรวจหลักฐานและเลือกแพ็กเกจให้ แล้วติดต่อกลับทาง LINE ครับ\nข้อความนี้ยังไม่ใช่การยืนยันแพ็กเกจหรือวันนัดหมาย`}
export function newRegistrationAlertText(r:{name:string;plate:string;province:string;services:string}){return `BJ Carcare มีรายการลงทะเบียนใหม่ 🔔\nลูกค้า: ${clean(r.name,80)}\nรถทะเบียน: ${clean(r.plate,30)} ${clean(r.province,60)}\nบริการ: ${selectedServices(r.services)}\nกรุณาเปิดหลังบ้านเพื่อตรวจสลิปและเลือกแพ็กเกจ\nhttps://bj-carcare-service.bjprogroup.chatgpt.site/`}
export async function pushLine(token:string,recipient:string,payload:string,retryKey:string,fetcher:typeof fetch=fetch){if(!token||!/^U[0-9a-f]{32}$/.test(recipient))throw Error('LINE_CONFIG_INVALID');try{const result=await fetcher('https://api.line.me/v2/bot/message/push',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Line-Retry-Key':retryKey},body:JSON.stringify({to:recipient,messages:JSON.parse(payload)}),signal:AbortSignal.timeout(15000)});return {state:retryDecision(result.status,result.headers.get('x-line-accepted-request-id')),code:result.status}}catch{return {state:'retry',code:0}}}
